
import { EtsyListing } from "app/etsy/listing";
import { EtsySection } from "app/etsy/section";

export type EtsyShop = {
    shop_id?: number,
    shop_name?: string,
    user_id?: number,
    creation_tsz?: number,
    title?: string,
    announcement?: string,
    currency_code?: string,
    is_vacation?: boolean,
    vacation_message?: string,
    sale_message?: string,
    digital_sale_message?: string,
    last_updated_tsz?: number,
    listing_active_count?: number,
    digital_listing_count?: number,
    login_name?: string,
    accepts_custom_requests?: boolean,
    policy_welcome?: string,
    policy_payment?: string,
    policy_shipping?: string,
    policy_refunds?: string,
    policy_additional?: string,
    policy_seller_info?: string,
    policy_updated_tsz?: number,
    policy_has_private_receipt_info?: boolean,
    vacation_autoreply?: string,
    url?: string,
    image_url_760x100?: string,
    num_favorers?: number,
    languages?: string[],
    upcoming_local_event_id?: number,
    icon_url_fullxfull?: string,
    is_using_structured_policies?: boolean,
    has_onboarded_structured_policies?: boolean,
    has_unstructured_policies?: boolean,
    include_dispute_form_link?: boolean,
    Listings?: EtsyListing[],
    Sections?: EtsySection,
};
